### ISSUE TITLE
Visit FirstTech to make account changes

### ISSUE THREAD

**Issue by reidab** [stumpsyn/stumpsyn#11]
@reidab and @kcomandich need to go to First Tech and make changes to the account signers. 

* Bring minutes showing changes in board membership
* Figure out if we can disassociate the account from @christi3k's email address / SSN (@reidab tried this at some point in the past, and it seemed hopeful, but has since forgotten all he learned)
* Add @kcomandich and @vosechu to the account

**Comment by reidab** [comment]
We've scheduled time to do this on Wednesday afternoon.

**Comment by reidab** [comment]
I called First Tech this afternoon to figure out how to make these changes. To change the signers, we need a copy of the relevant meeting minutes signed by all current board members and a new business signature card. I've gotten this paperwork from them and am going to try to get signatures from everyone before we go to FT tomorrow.

For the online account access, it sounds like we need to move away from using a single username to access the bank, and instead set up individual accounts for each board member. We can make this update after we update the signers.

**Comment by reidab** [comment]
I've gotten @christi3k's info on the paperwork and will meet up with @vosechu around 2:00 to get his.

**Comment by kcomandich** [comment]
@reidab & I visited First Tech and succesfully:
* changed the signers to current board members (@christi3k @reidab @vosechu & myself)
* received debit card for myself, one was mailed to @vosechu 
* set up separate online logins for each of us, so we no longer all use @christi3k's login.
