### ISSUE TITLE
Follow-up with 2015 insurance payments

### ISSUE THREAD

**Issue by christi3k** [stumpsyn/stumpsyn#2]

**Comment by christi3k** [comment]
Linda from WSC got back to me and let me know we were setup for agency bill for our gen liability. I have the details now about how to pay. Should I go ahead and issue the virtual check, or to @reidab or @kcomandich want to do this? I've forwarded the relevant email to treasurer@.

**Comment by reidab** [comment]
I think you can go ahead and issue the payment — I'm at a lecture and away from my computer for a bit.

**Comment by christi3k** [comment]
Payment made. I'm gonna close this out but we should keep an eye out for our renewed policy in the mail.
