### ISSUE TITLE
Prep and mail 2014 year end fundraiser thank yous

### ISSUE THREAD

**Issue by christi3k** [stumpsyn/stumpsyn#3]

**Comment by christi3k** [comment]
I'm it right now. Need to write body of cards and then hand off to @reidab. Meanwhile, @vosechu is prepping the mailing labels

**Comment by christi3k** [comment]
I've written thank you text in all the cards. These are ready for @reidab to sign. I'm downtown today and can hand them off.

**Comment by kcomandich** [comment]
completed and mailed! :mailbox_with_mail:
