### ISSUE TITLE
Announce board election results + 2016 board

### ISSUE THREAD

**Issue by christi3k** [stumpsyn/stumpsyn#30]
These announcements need to be published in order: #30, #27, #35, then #31.

**Comment by christi3k** [comment]
draft, please review + comment (or edit directly): http://stumptownsyndicate.org/?p=477&preview=true

**Comment by elea** [comment]
FYI I looked through and directly edited a few bits (added missing words to sentences and tweaked wording to make the announcement flow a bit better).

**Comment by christi3k** [comment]
Thanks to everyone who reviewed + edited. 

I’ve added Lenon’s bio. I’m scheduling this to post tomorrow, 1/20, at 9:15 PST.

If you notice anything that needs changing before then, please go ahead and make the change.

**Comment by elea** [comment]
This was done in Jan per the previous comment.
