### ISSUE TITLE
Investigate third-party mail sender (e.g. Mailgun, Mandrill)

### ISSUE THREAD

**Issue by christi3k** [stumpsyn/stumpsyn#36]
Emails generated by our servers (e.g. Wordpress, Mediawiki, etc.) often end up in people's spam folders. Using a third-party mailer that is well known might prevent this.

**Comment by reidab** [comment]
We're already using Mandrill for OSB outbound email, so it would be fairly easy to reuse that account.

**Comment by ed-g** [comment]
Tech: we need to fix mandril, they’re no longer offering the service we were using (we’re not on monthly) we’ll want to replace with other option, or decide to pay them monthly. AWS is one option. Just the emails from OCW for example acceptance emails are sent from server, long term we’ll want access from other Syndicate services. We may have been on free tier. Pricing should be near what AWS charges, we want pricing based on what we send, not on long term contract. No monthly fee. http://mailchimp.com/pricing/all/ 
We need to get this figured out before April 22nd.
Coordinate with Reid about how the configuration works, make sure he hasn’t updated it already.
One option, update Mailchimp account & possibly mailchimp credentials.
AWS, need to request to be moved out of sandbox -- creds in lastpass account.
Sounds like AWS limits are more than sufficient.
Make sure that delivery receipts don’t crash the server, rate limit or use queue.

**Comment by kcomandich** [comment]
Following because I'm updating compticketeer to not use Mandrill either.

BTW My emails from them say we have until April 27th.

**Comment by ed-g** [comment]
Sounds like OCW config at /var/www/osbridge-ocw/shared/config/secrets.yml has been updated to use AWS but it may or may not be working.

**Comment by reidab** [comment]
Because I hit this the last time I set up AWS' SES for a project: http://docs.aws.amazon.com/ses/latest/DeveloperGuide/request-production-access.html
